### Cálculo de la matriz inversa

$$ A^{-1} = \frac{1}{\left|A \right|} \cdot \mathbf{adj}\left(A \right)^T $$

#### Cálculo de la matriz adjunta 


$$ \mathbf{adj}\left(A_{2 \times 2} \right) = \begin{pmatrix} a_{22} & -a_{21} \\ -a_{22} & a_{11} \end{pmatrix} $$


$$ \mathbf{adj}\left(A_{3 \times 3} \right) = \begin{pmatrix}
            +
            \begin{vmatrix}
                a_{22} & a_{23} \\
                a_{32} & a_{33}
            \end{vmatrix} &
            -
            \begin{vmatrix}
                a_{12} & a_{13} \\
                a_{32} & a_{33}
            \end{vmatrix} &
            +
            \begin{vmatrix}
                a_{12} & a_{13} \\
                a_{22} & a_{23} \\
            \end{vmatrix} \\[1.5em]
            -
            \begin{vmatrix}
                a_{21} & a_{23} \\
                a_{31} & a_{33}
            \end{vmatrix} &
            +
            \begin{vmatrix}
                a_{11} & a_{13} \\
                a_{31} & a_{33}
            \end{vmatrix}&
            -
            \begin{vmatrix}
                a_{11} &  a_{13} \\
                a_{21} &  a_{23}
            \end{vmatrix} \\[1.5em]
            +
            \begin{vmatrix}
                a_{21} & a_{22} \\
                a_{31} & a_{32}
            \end{vmatrix} &
            -
            \begin{vmatrix}
            a_{11} & a_{12} \\
            a_{21} & a_{22}
            \end{vmatrix} &
            +
            \begin{vmatrix}
                a_{11} & a_{12} \\
                a_{21} & a_{22}
            \end{vmatrix}
        \end{pmatrix} $$



#### Programación de la matriz adjunta de una matriz 2x2

In [1]:
import numpy as np 

In [2]:
def adjunta_2x2(M):

    A = np.array([[M[1,1],-M[1,0]],
                    [-M[0,1],M[0,0]]])
    return A 


In [3]:
A = np.array([[1,-1],[2,3]])

In [4]:
adjunta_2x2(A)

array([[ 3, -2],
       [ 1,  1]])

### Programación de la adjunta de una matriz de N x N

In [18]:

def quitar_linea(index,M):
    """Función que elimina la fila y la columna según el índice indicado
    """
    m=[] #Submatriz 
    M = list(M) #Convertimos en lista el array de entrada M
    for i in range(len(M)):
        hh=[]
        for j in range(len(M)):
            if(i==index[0] or j==index[1]): #Si el indice no es el que hemos pasado apendizamos
                pass
            else:
                hh.append(M[i][j])
        if(hh!=[]):
            m.append(hh)
    return np.array(m)




In [19]:
P = np.array([[3,4,5],[3,6,7],[1,2,6]])
P

array([[3, 4, 5],
       [3, 6, 7],
       [1, 2, 6]])

In [22]:
quitar_linea([1,1],P)

array([[3, 5],
       [1, 6]])

In [29]:
def adjunta_NxN(M):
    """Función que cálcula la matriz adjunta de M
    """
    Adj = np.zeros_like(M) #Matriz de ceros con forma de M

    for i in range(len(M)):
        for j in range(len(M)):
            m = quitar_linea([i,j],M)
            Adj[i,j] = np.linalg.det(m)*(-1)**(i+j) #Determinante de la submatriz multiplicado por -1 o 1 
    return Adj



In [27]:
P

array([[3, 4, 5],
       [3, 6, 7],
       [1, 2, 6]])

In [33]:
adjunta_NxN(P)

array([[ 22, -11,   0],
       [-14,  13,  -2],
       [ -2,  -6,   6]])

### Programación de la inversa de una matriz N x N

In [44]:
def invertir_matriz(M):
    assert (np.linalg.det(M)!=0),"El determinante de la matriz es nulo"
    Inv = 1/np.linalg.det(M)*adjunta_NxN(M).T #Fórmula para calcular la inversa
    return Inv
    
    
        

In [36]:
P

array([[3, 4, 5],
       [3, 6, 7],
       [1, 2, 6]])

In [45]:
invertir_matriz(P)

array([[ 1.        , -0.63636364, -0.09090909],
       [-0.5       ,  0.59090909, -0.27272727],
       [ 0.        , -0.09090909,  0.27272727]])

In [46]:
np.linalg.inv(P)

array([[ 1.00000000e+00, -6.36363636e-01, -9.09090909e-02],
       [-5.00000000e-01,  5.90909091e-01, -2.72727273e-01],
       [ 1.51394049e-17, -9.09090909e-02,  2.72727273e-01]])

In [52]:
Merror = np.array([[0,0],[-1,3]])
Merror


array([[ 0,  0],
       [-1,  3]])

In [53]:
invertir_matriz(Merror)

AssertionError: El determinante de la matriz es nulo