# Cálculo de la matriz transpuesta

In [1]:
import numpy as np

In [2]:
A = np.array([[1,2],[3,4]])
A

array([[1, 2],
       [3, 4]])

In [3]:
A.T

array([[1, 3],
       [2, 4]])

In [4]:
B = np.array([[1,2],[3,4],[5,6]])
B

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
B.T

array([[1, 3, 5],
       [2, 4, 6]])

In [6]:
B.shape

(3, 2)

In [7]:
B.T.shape

(2, 3)

In [23]:
def transponer_matriz(M):
    """Función que devuelve la matriz transpuesta 
    """
    n_filas,n_columnas = M.shape    #Determinamos la forma de la matriz de entrada
    n_filas,n_columnas = n_columnas,n_filas #intercambio de valores de filas columnas
    A = np.zeros((n_filas,n_columnas)) #Creamos una matriz de ceros con cambiando el numero de filas y de columnas
    # A = np.zeros_like(M).T
    
    for i in range(n_filas):
        for j in range(n_columnas):
            A[i,j]=M[j,i] 

    return A


### Prueba de la función

In [24]:
M = np.array([[1,2,3],[1,4,-3],[1,-3,4],[2,1,5]])
M

array([[ 1,  2,  3],
       [ 1,  4, -3],
       [ 1, -3,  4],
       [ 2,  1,  5]])

In [25]:
M.T

array([[ 1,  1,  1,  2],
       [ 2,  4, -3,  1],
       [ 3, -3,  4,  5]])

In [28]:
transponer_matriz(M)

array([[ 1.,  1.,  1.,  2.],
       [ 2.,  4., -3.,  1.],
       [ 3., -3.,  4.,  5.]])