# Introducción a las matrices en Python

### Importación de módulos

En esta sesión vamos a introducir el paquete **Numpy**. Para más información en la web: [Numpy](https://www.numpy.org)

In [1]:
import numpy as np #Importamos numpy como np para simplificar

### Primera matriz con numpy
Por ejemplo:
 $$ A = 
\begin{pmatrix}
5 & -4 & 2\\
2 & -1 & 1\\
-4 & 4 & -1
\end{pmatrix}
 $$

In [13]:
A = np.array([ #Utilizamos un array de 3x3 elementos
    [5,-4,2],
    [2,-1,1],
    [-4,4,1],
]) 
A

array([[ 5, -4,  2],
       [ 2, -1,  1],
       [-4,  4,  1]])

### Dimension de la matriz

In [14]:
Dimension = A.shape #Utilizamos la propiedad del array: shape
print(Dimension)


(3, 3)


In [16]:
#Número de filas 
N_filas = Dimension[0]

#Número de columnas
N_cols = Dimension[1]

print(f"El número de filas de A es {N_filas} y de columnas es {N_cols}")

El número de filas de A es 3 y de columnas es 3


### Matriz Transpuesta


In [20]:
A.T #Para la transpuesta utilizamos la propiedad T

array([[ 5,  2, -4],
       [-4, -1,  4],
       [ 2,  1,  1]])

In [21]:
A


array([[ 5, -4,  2],
       [ 2, -1,  1],
       [-4,  4,  1]])

### Matriz Identidad

In [69]:
Id = np.eye(5)
Id

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Extracción de submatrices

In [26]:
v1 = A[:,0] #Primera columna de A
v1

array([ 5,  2, -4])

In [28]:
v2 = A[1,:] #Segunda fila de A
v2

array([ 2, -1,  1])

In [32]:
v3 = A[1:3,:] #Submatriz A 
v3

array([[ 2, -1,  1],
       [-4,  4,  1]])

## Operaciones con Matrices
- Suma 
- Resta
- Multiplicación matricial 
- Multiplicación elemento a elemento
- División elemento a elemento Producto/división por un número

In [48]:
B = np.array([
    [1,3,5],
    [4,5,-2],
    [7,0.2,3]
])
print("A = ", A,"\n\n","B = ",B)

A =  [[ 5 -4  2]
 [ 2 -1  1]
 [-4  4  1]] 

 B =  [[ 1.   3.   5. ]
 [ 4.   5.  -2. ]
 [ 7.   0.2  3. ]]


In [36]:
M_suma = A+B
M_suma

array([[ 6, -1,  7],
       [ 6,  4, -1],
       [ 3,  6,  4]])

In [41]:
M_resta = A-B
M_resta

array([[  4,  -7,  -3],
       [ -2,  -6,   3],
       [-11,   2,  -2]])

In [42]:
M_prod_matricial = A @ B
M_prod_matricial

array([[  3,  -1,  39],
       [  5,   3,  15],
       [ 19,  10, -25]])

In [44]:
M_prod_elem = A*B
M_prod_elem

array([[  5, -12,  10],
       [  8,  -5,  -2],
       [-28,   8,   3]])

In [49]:
M_div_elem = A/B
M_div_elem

array([[ 5.        , -1.33333333,  0.4       ],
       [ 0.5       , -0.2       , -0.5       ],
       [-0.57142857, 20.        ,  0.33333333]])

In [68]:
5*A

array([[ 25, -20,  10],
       [ 10,  -5,   5],
       [-20,  20,   5]])

## Determinante de la matriz

La función del determinante se encuentra dentro de la librería `numpy.linalg` de algebra lineal.

In [63]:
from numpy.linalg import det, inv

In [64]:
D_A = det(A) 
D_B = det(B)
D_A, D_B

(7.000000000000001, -233.60000000000002)

In [65]:
det(A@B)

-1635.199999999999

In [66]:
D_A*D_B

-1635.2000000000003

In [67]:
inv(A)

array([[-0.71428571,  1.71428571, -0.28571429],
       [-0.85714286,  1.85714286, -0.14285714],
       [ 0.57142857, -0.57142857,  0.42857143]])